version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.17.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{checksum "package.json"}}
            - app-
      - run:
          name: Install yarn
          command: yarn install -g yarn
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: app-{{checksum "package.json"}}

  deploy-to-aws-s3:
    docker:
      - image: circleci/node:16.17.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      - run:
          name: Install yarn
          command: yarn install -g yarn
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build Project
          command: |
            yarn install
            yarn run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build Successfully"
      - run:
          name: deploy-to-aws-s3
          command: |
            if ["${CIRCLE_BRANCH}" == "master"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_PROD_BUCKET} --delete
            elif ["${CIRCLE_BRANCH}" == "staging"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_STAGING_BUCKET} --delete
            else
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_DEV_BUCKET} --delete
            fi
      - run:
          name: deploy-to-aws-cloudfront
          command: |
            aws configure set preview.cloudfront true
            if ["${CIRCLE_BRANCH}" == "master"]
            then
              aws cloudfront  create-invalidation --distribution-id ${PROD_DISTRIBUTION_ID} --path /\*
            elif ["${CIRCLE_BRANCH}" == "staging"]
            then
              aws cloudfront  create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --path /\*
            else
              aws cloudfront  create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --path /\*
            fi

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws-s3:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - deploy-to-aws-cloudfront:
          requires:
            - deploy-to-aws-s3
          filters:
            branches:
              only:
                - develop
                - staging
                - master
